// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: bcrd.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BcrdService_GetShopsTotal_FullMethodName  = "/bcrd.BcrdService/GetShopsTotal"
	BcrdService_GetShops_FullMethodName       = "/bcrd.BcrdService/GetShops"
	BcrdService_GetShop_FullMethodName        = "/bcrd.BcrdService/GetShop"
	BcrdService_AddStamp_FullMethodName       = "/bcrd.BcrdService/AddStamp"
	BcrdService_DeleteStamp_FullMethodName    = "/bcrd.BcrdService/DeleteStamp"
	BcrdService_MergeUserStamp_FullMethodName = "/bcrd.BcrdService/MergeUserStamp"
)

// BcrdServiceClient is the client API for BcrdService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BcrdServiceClient interface {
	// 店舗総数取得
	GetShopsTotal(ctx context.Context, in *ShopsTotalRequest, opts ...grpc.CallOption) (*ShopsTotalResponse, error)
	// 店舗情報取得
	GetShops(ctx context.Context, in *ShopsRequest, opts ...grpc.CallOption) (*ShopsResponse, error)
	// 店舗情報取得
	GetShop(ctx context.Context, in *ShopRequest, opts ...grpc.CallOption) (*ShopResponse, error)
	// スタンプ追加
	AddStamp(ctx context.Context, in *StampRequest, opts ...grpc.CallOption) (*StampResponse, error)
	// スタンプ削除
	DeleteStamp(ctx context.Context, in *StampRequest, opts ...grpc.CallOption) (*StampResponse, error)
	// ユーザーログイン
	MergeUserStamp(ctx context.Context, in *MergeUserStampRequest, opts ...grpc.CallOption) (*MergeUserStampResponse, error)
}

type bcrdServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBcrdServiceClient(cc grpc.ClientConnInterface) BcrdServiceClient {
	return &bcrdServiceClient{cc}
}

func (c *bcrdServiceClient) GetShopsTotal(ctx context.Context, in *ShopsTotalRequest, opts ...grpc.CallOption) (*ShopsTotalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShopsTotalResponse)
	err := c.cc.Invoke(ctx, BcrdService_GetShopsTotal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcrdServiceClient) GetShops(ctx context.Context, in *ShopsRequest, opts ...grpc.CallOption) (*ShopsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShopsResponse)
	err := c.cc.Invoke(ctx, BcrdService_GetShops_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcrdServiceClient) GetShop(ctx context.Context, in *ShopRequest, opts ...grpc.CallOption) (*ShopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShopResponse)
	err := c.cc.Invoke(ctx, BcrdService_GetShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcrdServiceClient) AddStamp(ctx context.Context, in *StampRequest, opts ...grpc.CallOption) (*StampResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StampResponse)
	err := c.cc.Invoke(ctx, BcrdService_AddStamp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcrdServiceClient) DeleteStamp(ctx context.Context, in *StampRequest, opts ...grpc.CallOption) (*StampResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StampResponse)
	err := c.cc.Invoke(ctx, BcrdService_DeleteStamp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bcrdServiceClient) MergeUserStamp(ctx context.Context, in *MergeUserStampRequest, opts ...grpc.CallOption) (*MergeUserStampResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergeUserStampResponse)
	err := c.cc.Invoke(ctx, BcrdService_MergeUserStamp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BcrdServiceServer is the server API for BcrdService service.
// All implementations must embed UnimplementedBcrdServiceServer
// for forward compatibility.
type BcrdServiceServer interface {
	// 店舗総数取得
	GetShopsTotal(context.Context, *ShopsTotalRequest) (*ShopsTotalResponse, error)
	// 店舗情報取得
	GetShops(context.Context, *ShopsRequest) (*ShopsResponse, error)
	// 店舗情報取得
	GetShop(context.Context, *ShopRequest) (*ShopResponse, error)
	// スタンプ追加
	AddStamp(context.Context, *StampRequest) (*StampResponse, error)
	// スタンプ削除
	DeleteStamp(context.Context, *StampRequest) (*StampResponse, error)
	// ユーザーログイン
	MergeUserStamp(context.Context, *MergeUserStampRequest) (*MergeUserStampResponse, error)
	mustEmbedUnimplementedBcrdServiceServer()
}

// UnimplementedBcrdServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBcrdServiceServer struct{}

func (UnimplementedBcrdServiceServer) GetShopsTotal(context.Context, *ShopsTotalRequest) (*ShopsTotalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShopsTotal not implemented")
}
func (UnimplementedBcrdServiceServer) GetShops(context.Context, *ShopsRequest) (*ShopsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShops not implemented")
}
func (UnimplementedBcrdServiceServer) GetShop(context.Context, *ShopRequest) (*ShopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShop not implemented")
}
func (UnimplementedBcrdServiceServer) AddStamp(context.Context, *StampRequest) (*StampResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddStamp not implemented")
}
func (UnimplementedBcrdServiceServer) DeleteStamp(context.Context, *StampRequest) (*StampResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStamp not implemented")
}
func (UnimplementedBcrdServiceServer) MergeUserStamp(context.Context, *MergeUserStampRequest) (*MergeUserStampResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MergeUserStamp not implemented")
}
func (UnimplementedBcrdServiceServer) mustEmbedUnimplementedBcrdServiceServer() {}
func (UnimplementedBcrdServiceServer) testEmbeddedByValue()                     {}

// UnsafeBcrdServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BcrdServiceServer will
// result in compilation errors.
type UnsafeBcrdServiceServer interface {
	mustEmbedUnimplementedBcrdServiceServer()
}

func RegisterBcrdServiceServer(s grpc.ServiceRegistrar, srv BcrdServiceServer) {
	// If the following call pancis, it indicates UnimplementedBcrdServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BcrdService_ServiceDesc, srv)
}

func _BcrdService_GetShopsTotal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopsTotalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcrdServiceServer).GetShopsTotal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcrdService_GetShopsTotal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcrdServiceServer).GetShopsTotal(ctx, req.(*ShopsTotalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcrdService_GetShops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcrdServiceServer).GetShops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcrdService_GetShops_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcrdServiceServer).GetShops(ctx, req.(*ShopsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcrdService_GetShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcrdServiceServer).GetShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcrdService_GetShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcrdServiceServer).GetShop(ctx, req.(*ShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcrdService_AddStamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StampRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcrdServiceServer).AddStamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcrdService_AddStamp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcrdServiceServer).AddStamp(ctx, req.(*StampRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcrdService_DeleteStamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StampRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcrdServiceServer).DeleteStamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcrdService_DeleteStamp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcrdServiceServer).DeleteStamp(ctx, req.(*StampRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BcrdService_MergeUserStamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeUserStampRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BcrdServiceServer).MergeUserStamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BcrdService_MergeUserStamp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BcrdServiceServer).MergeUserStamp(ctx, req.(*MergeUserStampRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BcrdService_ServiceDesc is the grpc.ServiceDesc for BcrdService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BcrdService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bcrd.BcrdService",
	HandlerType: (*BcrdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetShopsTotal",
			Handler:    _BcrdService_GetShopsTotal_Handler,
		},
		{
			MethodName: "GetShops",
			Handler:    _BcrdService_GetShops_Handler,
		},
		{
			MethodName: "GetShop",
			Handler:    _BcrdService_GetShop_Handler,
		},
		{
			MethodName: "AddStamp",
			Handler:    _BcrdService_AddStamp_Handler,
		},
		{
			MethodName: "DeleteStamp",
			Handler:    _BcrdService_DeleteStamp_Handler,
		},
		{
			MethodName: "MergeUserStamp",
			Handler:    _BcrdService_MergeUserStamp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bcrd.proto",
}
