// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: bcrd.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchType int32

const (
	SearchType_SEARCH_TYPE_IN_CURRENT_SALES  SearchType = 0
	SearchType_SEARCH_TYPE_NOT_YET           SearchType = 1
	SearchType_SEARCH_TYPE_IRREGULAR_HOLIDAY SearchType = 2
)

// Enum value maps for SearchType.
var (
	SearchType_name = map[int32]string{
		0: "SEARCH_TYPE_IN_CURRENT_SALES",
		1: "SEARCH_TYPE_NOT_YET",
		2: "SEARCH_TYPE_IRREGULAR_HOLIDAY",
	}
	SearchType_value = map[string]int32{
		"SEARCH_TYPE_IN_CURRENT_SALES":  0,
		"SEARCH_TYPE_NOT_YET":           1,
		"SEARCH_TYPE_IRREGULAR_HOLIDAY": 2,
	}
)

func (x SearchType) Enum() *SearchType {
	p := new(SearchType)
	*p = x
	return p
}

func (x SearchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchType) Descriptor() protoreflect.EnumDescriptor {
	return file_bcrd_proto_enumTypes[0].Descriptor()
}

func (SearchType) Type() protoreflect.EnumType {
	return &file_bcrd_proto_enumTypes[0]
}

func (x SearchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchType.Descriptor instead.
func (SearchType) EnumDescriptor() ([]byte, []int) {
	return file_bcrd_proto_rawDescGZIP(), []int{0}
}

type SortOrderType int32

const (
	SortOrderType_SORT_ORDER_NO       SortOrderType = 0
	SortOrderType_SORT_ORDER_DISTANCE SortOrderType = 1
)

// Enum value maps for SortOrderType.
var (
	SortOrderType_name = map[int32]string{
		0: "SORT_ORDER_NO",
		1: "SORT_ORDER_DISTANCE",
	}
	SortOrderType_value = map[string]int32{
		"SORT_ORDER_NO":       0,
		"SORT_ORDER_DISTANCE": 1,
	}
)

func (x SortOrderType) Enum() *SortOrderType {
	p := new(SortOrderType)
	*p = x
	return p
}

func (x SortOrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_bcrd_proto_enumTypes[1].Descriptor()
}

func (SortOrderType) Type() protoreflect.EnumType {
	return &file_bcrd_proto_enumTypes[1]
}

func (x SortOrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrderType.Descriptor instead.
func (SortOrderType) EnumDescriptor() ([]byte, []int) {
	return file_bcrd_proto_rawDescGZIP(), []int{1}
}

type Date struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day           int32                  `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Date) Reset() {
	*x = Date{}
	mi := &file_bcrd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Date) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Date) ProtoMessage() {}

func (x *Date) ProtoReflect() protoreflect.Message {
	mi := &file_bcrd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Date.ProtoReflect.Descriptor instead.
func (*Date) Descriptor() ([]byte, []int) {
	return file_bcrd_proto_rawDescGZIP(), []int{0}
}

func (x *Date) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Date) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *Date) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	StartDate     *Date                  `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *Date                  `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_bcrd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_bcrd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_bcrd_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Event) GetStartDate() *Date {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Event) GetEndDate() *Date {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type Shop struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId            int64                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Year               int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	No                 int32                  `protobuf:"varint,4,opt,name=no,proto3" json:"no,omitempty"`
	ShopName           string                 `protobuf:"bytes,5,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`
	ImageUrl           string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	GoogleUrl          string                 `protobuf:"bytes,7,opt,name=google_url,json=googleUrl,proto3" json:"google_url,omitempty"`
	TabelogUrl         string                 `protobuf:"bytes,8,opt,name=tabelog_url,json=tabelogUrl,proto3" json:"tabelog_url,omitempty"`
	OfficialUrl        string                 `protobuf:"bytes,9,opt,name=official_url,json=officialUrl,proto3" json:"official_url,omitempty"`
	InstagramUrl       string                 `protobuf:"bytes,10,opt,name=instagram_url,json=instagramUrl,proto3" json:"instagram_url,omitempty"`
	Address            string                 `protobuf:"bytes,11,opt,name=address,proto3" json:"address,omitempty"`
	BusinessDays       string                 `protobuf:"bytes,12,opt,name=business_days,json=businessDays,proto3" json:"business_days,omitempty"`
	RegularHoliday     string                 `protobuf:"bytes,13,opt,name=regular_holiday,json=regularHoliday,proto3" json:"regular_holiday,omitempty"`
	IsOpenHoliday      bool                   `protobuf:"varint,14,opt,name=is_open_holiday,json=isOpenHoliday,proto3" json:"is_open_holiday,omitempty"`
	IsIrregularHoliday bool                   `protobuf:"varint,15,opt,name=is_irregular_holiday,json=isIrregularHoliday,proto3" json:"is_irregular_holiday,omitempty"`
	Latitude           float64                `protobuf:"fixed64,16,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude          float64                `protobuf:"fixed64,17,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Distance           string                 `protobuf:"bytes,18,opt,name=distance,proto3" json:"distance,omitempty"`
	WeekNumber         int32                  `protobuf:"varint,19,opt,name=week_number,json=weekNumber,proto3" json:"week_number,omitempty"`
	DayOfWeek          int32                  `protobuf:"varint,20,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"`
	StartTime          string                 `protobuf:"bytes,21,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime            string                 `protobuf:"bytes,22,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IsHoliday          bool                   `protobuf:"varint,23,opt,name=is_holiday,json=isHoliday,proto3" json:"is_holiday,omitempty"`
	InCurrentSales     bool                   `protobuf:"varint,24,opt,name=in_current_sales,json=inCurrentSales,proto3" json:"in_current_sales,omitempty"`
	IsStamped          bool                   `protobuf:"varint,25,opt,name=is_stamped,json=isStamped,proto3" json:"is_stamped,omitempty"`
	NumberOfTimes      int32                  `protobuf:"varint,26,opt,name=number_of_times,json=numberOfTimes,proto3" json:"number_of_times,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Shop) Reset() {
	*x = Shop{}
	mi := &file_bcrd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shop) ProtoMessage() {}

func (x *Shop) ProtoReflect() protoreflect.Message {
	mi := &file_bcrd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shop.ProtoReflect.Descriptor instead.
func (*Shop) Descriptor() ([]byte, []int) {
	return file_bcrd_proto_rawDescGZIP(), []int{2}
}

func (x *Shop) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Shop) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *Shop) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Shop) GetNo() int32 {
	if x != nil {
		return x.No
	}
	return 0
}

func (x *Shop) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *Shop) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Shop) GetGoogleUrl() string {
	if x != nil {
		return x.GoogleUrl
	}
	return ""
}

func (x *Shop) GetTabelogUrl() string {
	if x != nil {
		return x.TabelogUrl
	}
	return ""
}

func (x *Shop) GetOfficialUrl() string {
	if x != nil {
		return x.OfficialUrl
	}
	return ""
}

func (x *Shop) GetInstagramUrl() string {
	if x != nil {
		return x.InstagramUrl
	}
	return ""
}

func (x *Shop) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Shop) GetBusinessDays() string {
	if x != nil {
		return x.BusinessDays
	}
	return ""
}

func (x *Shop) GetRegularHoliday() string {
	if x != nil {
		return x.RegularHoliday
	}
	return ""
}

func (x *Shop) GetIsOpenHoliday() bool {
	if x != nil {
		return x.IsOpenHoliday
	}
	return false
}

func (x *Shop) GetIsIrregularHoliday() bool {
	if x != nil {
		return x.IsIrregularHoliday
	}
	return false
}

func (x *Shop) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Shop) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Shop) GetDistance() string {
	if x != nil {
		return x.Distance
	}
	return ""
}

func (x *Shop) GetWeekNumber() int32 {
	if x != nil {
		return x.WeekNumber
	}
	return 0
}

func (x *Shop) GetDayOfWeek() int32 {
	if x != nil {
		return x.DayOfWeek
	}
	return 0
}

func (x *Shop) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Shop) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *Shop) GetIsHoliday() bool {
	if x != nil {
		return x.IsHoliday
	}
	return false
}

func (x *Shop) GetInCurrentSales() bool {
	if x != nil {
		return x.InCurrentSales
	}
	return false
}

func (x *Shop) GetIsStamped() bool {
	if x != nil {
		return x.IsStamped
	}
	return false
}

func (x *Shop) GetNumberOfTimes() int32 {
	if x != nil {
		return x.NumberOfTimes
	}
	return 0
}

type ShopLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId        int64                  `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopLocation) Reset() {
	*x = ShopLocation{}
	mi := &file_bcrd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopLocation) ProtoMessage() {}

func (x *ShopLocation) ProtoReflect() protoreflect.Message {
	mi := &file_bcrd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopLocation.ProtoReflect.Descriptor instead.
func (*ShopLocation) Descriptor() ([]byte, []int) {
	return file_bcrd_proto_rawDescGZIP(), []int{3}
}

func (x *ShopLocation) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShopLocation) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *ShopLocation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *ShopLocation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *ShopLocation) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type ShopTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopId        int64                  `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	WeekNumber    int32                  `protobuf:"varint,3,opt,name=week_number,json=weekNumber,proto3" json:"week_number,omitempty"`
	DayOfWeek     int32                  `protobuf:"varint,4,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"`
	StartTime     string                 `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IsHoliday     bool                   `protobuf:"varint,7,opt,name=is_holiday,json=isHoliday,proto3" json:"is_holiday,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopTime) Reset() {
	*x = ShopTime{}
	mi := &file_bcrd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopTime) ProtoMessage() {}

func (x *ShopTime) ProtoReflect() protoreflect.Message {
	mi := &file_bcrd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopTime.ProtoReflect.Descriptor instead.
func (*ShopTime) Descriptor() ([]byte, []int) {
	return file_bcrd_proto_rawDescGZIP(), []int{4}
}

func (x *ShopTime) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShopTime) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *ShopTime) GetWeekNumber() int32 {
	if x != nil {
		return x.WeekNumber
	}
	return 0
}

func (x *ShopTime) GetDayOfWeek() int32 {
	if x != nil {
		return x.DayOfWeek
	}
	return 0
}

func (x *ShopTime) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ShopTime) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ShopTime) GetIsHoliday() bool {
	if x != nil {
		return x.IsHoliday
	}
	return false
}

type ShopsTotalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopsTotalRequest) Reset() {
	*x = ShopsTotalRequest{}
	mi := &file_bcrd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopsTotalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopsTotalRequest) ProtoMessage() {}

func (x *ShopsTotalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bcrd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopsTotalRequest.ProtoReflect.Descriptor instead.
func (*ShopsTotalRequest) Descriptor() ([]byte, []int) {
	return file_bcrd_proto_rawDescGZIP(), []int{5}
}

func (x *ShopsTotalRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type ShopsTotalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalNum      int64                  `protobuf:"varint,1,opt,name=total_num,json=totalNum,proto3" json:"total_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopsTotalResponse) Reset() {
	*x = ShopsTotalResponse{}
	mi := &file_bcrd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopsTotalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopsTotalResponse) ProtoMessage() {}

func (x *ShopsTotalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bcrd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopsTotalResponse.ProtoReflect.Descriptor instead.
func (*ShopsTotalResponse) Descriptor() ([]byte, []int) {
	return file_bcrd_proto_rawDescGZIP(), []int{6}
}

func (x *ShopsTotalResponse) GetTotalNum() int64 {
	if x != nil {
		return x.TotalNum
	}
	return 0
}

type ShopsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchTypes   []SearchType           `protobuf:"varint,1,rep,packed,name=search_types,json=searchTypes,proto3,enum=bcrd.SearchType" json:"search_types,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	SortOrder     SortOrderType          `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3,enum=bcrd.SortOrderType" json:"sort_order,omitempty"`
	Latitude      float64                `protobuf:"fixed64,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopsRequest) Reset() {
	*x = ShopsRequest{}
	mi := &file_bcrd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopsRequest) ProtoMessage() {}

func (x *ShopsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bcrd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopsRequest.ProtoReflect.Descriptor instead.
func (*ShopsRequest) Descriptor() ([]byte, []int) {
	return file_bcrd_proto_rawDescGZIP(), []int{7}
}

func (x *ShopsRequest) GetSearchTypes() []SearchType {
	if x != nil {
		return x.SearchTypes
	}
	return nil
}

func (x *ShopsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ShopsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ShopsRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ShopsRequest) GetSortOrder() SortOrderType {
	if x != nil {
		return x.SortOrder
	}
	return SortOrderType_SORT_ORDER_NO
}

func (x *ShopsRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *ShopsRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type ShopsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shops         []*Shop                `protobuf:"bytes,1,rep,name=shops,proto3" json:"shops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopsResponse) Reset() {
	*x = ShopsResponse{}
	mi := &file_bcrd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopsResponse) ProtoMessage() {}

func (x *ShopsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bcrd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopsResponse.ProtoReflect.Descriptor instead.
func (*ShopsResponse) Descriptor() ([]byte, []int) {
	return file_bcrd_proto_rawDescGZIP(), []int{8}
}

func (x *ShopsResponse) GetShops() []*Shop {
	if x != nil {
		return x.Shops
	}
	return nil
}

type ShopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShopId        int64                  `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopRequest) Reset() {
	*x = ShopRequest{}
	mi := &file_bcrd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopRequest) ProtoMessage() {}

func (x *ShopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bcrd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopRequest.ProtoReflect.Descriptor instead.
func (*ShopRequest) Descriptor() ([]byte, []int) {
	return file_bcrd_proto_rawDescGZIP(), []int{9}
}

func (x *ShopRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ShopRequest) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

type ShopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shop          *Shop                  `protobuf:"bytes,1,opt,name=shop,proto3" json:"shop,omitempty"`
	IsEventPeriod bool                   `protobuf:"varint,2,opt,name=is_event_period,json=isEventPeriod,proto3" json:"is_event_period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopResponse) Reset() {
	*x = ShopResponse{}
	mi := &file_bcrd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopResponse) ProtoMessage() {}

func (x *ShopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bcrd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopResponse.ProtoReflect.Descriptor instead.
func (*ShopResponse) Descriptor() ([]byte, []int) {
	return file_bcrd_proto_rawDescGZIP(), []int{10}
}

func (x *ShopResponse) GetShop() *Shop {
	if x != nil {
		return x.Shop
	}
	return nil
}

func (x *ShopResponse) GetIsEventPeriod() bool {
	if x != nil {
		return x.IsEventPeriod
	}
	return false
}

type StampRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShopId        int64                  `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StampRequest) Reset() {
	*x = StampRequest{}
	mi := &file_bcrd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StampRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StampRequest) ProtoMessage() {}

func (x *StampRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bcrd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StampRequest.ProtoReflect.Descriptor instead.
func (*StampRequest) Descriptor() ([]byte, []int) {
	return file_bcrd_proto_rawDescGZIP(), []int{11}
}

func (x *StampRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StampRequest) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

type StampResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumberOfTimes int32                  `protobuf:"varint,1,opt,name=number_of_times,json=numberOfTimes,proto3" json:"number_of_times,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StampResponse) Reset() {
	*x = StampResponse{}
	mi := &file_bcrd_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StampResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StampResponse) ProtoMessage() {}

func (x *StampResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bcrd_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StampResponse.ProtoReflect.Descriptor instead.
func (*StampResponse) Descriptor() ([]byte, []int) {
	return file_bcrd_proto_rawDescGZIP(), []int{12}
}

func (x *StampResponse) GetNumberOfTimes() int32 {
	if x != nil {
		return x.NumberOfTimes
	}
	return 0
}

type MergeUserStampRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AnonymousUserId string                 `protobuf:"bytes,2,opt,name=anonymous_user_id,json=anonymousUserId,proto3" json:"anonymous_user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MergeUserStampRequest) Reset() {
	*x = MergeUserStampRequest{}
	mi := &file_bcrd_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeUserStampRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeUserStampRequest) ProtoMessage() {}

func (x *MergeUserStampRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bcrd_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeUserStampRequest.ProtoReflect.Descriptor instead.
func (*MergeUserStampRequest) Descriptor() ([]byte, []int) {
	return file_bcrd_proto_rawDescGZIP(), []int{13}
}

func (x *MergeUserStampRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MergeUserStampRequest) GetAnonymousUserId() string {
	if x != nil {
		return x.AnonymousUserId
	}
	return ""
}

type MergeUserStampResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StampNum      int32                  `protobuf:"varint,1,opt,name=stamp_num,json=stampNum,proto3" json:"stamp_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeUserStampResponse) Reset() {
	*x = MergeUserStampResponse{}
	mi := &file_bcrd_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeUserStampResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeUserStampResponse) ProtoMessage() {}

func (x *MergeUserStampResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bcrd_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeUserStampResponse.ProtoReflect.Descriptor instead.
func (*MergeUserStampResponse) Descriptor() ([]byte, []int) {
	return file_bcrd_proto_rawDescGZIP(), []int{14}
}

func (x *MergeUserStampResponse) GetStampNum() int32 {
	if x != nil {
		return x.StampNum
	}
	return 0
}

var File_bcrd_proto protoreflect.FileDescriptor

const file_bcrd_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"bcrd.proto\x12\x04bcrd\"B\n" +
	"\x04Date\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x10\n" +
	"\x03day\x18\x03 \x01(\x05R\x03day\"\x91\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12)\n" +
	"\n" +
	"start_date\x18\x04 \x01(\v2\n" +
	".bcrd.DateR\tstartDate\x12%\n" +
	"\bend_date\x18\x05 \x01(\v2\n" +
	".bcrd.DateR\aendDate\"\xba\x06\n" +
	"\x04Shop\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x03R\aeventId\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x0e\n" +
	"\x02no\x18\x04 \x01(\x05R\x02no\x12\x1b\n" +
	"\tshop_name\x18\x05 \x01(\tR\bshopName\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\x12\x1d\n" +
	"\n" +
	"google_url\x18\a \x01(\tR\tgoogleUrl\x12\x1f\n" +
	"\vtabelog_url\x18\b \x01(\tR\n" +
	"tabelogUrl\x12!\n" +
	"\fofficial_url\x18\t \x01(\tR\vofficialUrl\x12#\n" +
	"\rinstagram_url\x18\n" +
	" \x01(\tR\finstagramUrl\x12\x18\n" +
	"\aaddress\x18\v \x01(\tR\aaddress\x12#\n" +
	"\rbusiness_days\x18\f \x01(\tR\fbusinessDays\x12'\n" +
	"\x0fregular_holiday\x18\r \x01(\tR\x0eregularHoliday\x12&\n" +
	"\x0fis_open_holiday\x18\x0e \x01(\bR\risOpenHoliday\x120\n" +
	"\x14is_irregular_holiday\x18\x0f \x01(\bR\x12isIrregularHoliday\x12\x1a\n" +
	"\blatitude\x18\x10 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x11 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\bdistance\x18\x12 \x01(\tR\bdistance\x12\x1f\n" +
	"\vweek_number\x18\x13 \x01(\x05R\n" +
	"weekNumber\x12\x1e\n" +
	"\vday_of_week\x18\x14 \x01(\x05R\tdayOfWeek\x12\x1d\n" +
	"\n" +
	"start_time\x18\x15 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x16 \x01(\tR\aendTime\x12\x1d\n" +
	"\n" +
	"is_holiday\x18\x17 \x01(\bR\tisHoliday\x12(\n" +
	"\x10in_current_sales\x18\x18 \x01(\bR\x0einCurrentSales\x12\x1d\n" +
	"\n" +
	"is_stamped\x18\x19 \x01(\bR\tisStamped\x12&\n" +
	"\x0fnumber_of_times\x18\x1a \x01(\x05R\rnumberOfTimes\"\x8d\x01\n" +
	"\fShopLocation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\x03R\x06shopId\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\"\xcd\x01\n" +
	"\bShopTime\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\x03R\x06shopId\x12\x1f\n" +
	"\vweek_number\x18\x03 \x01(\x05R\n" +
	"weekNumber\x12\x1e\n" +
	"\vday_of_week\x18\x04 \x01(\x05R\tdayOfWeek\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\tR\aendTime\x12\x1d\n" +
	"\n" +
	"is_holiday\x18\a \x01(\bR\tisHoliday\"'\n" +
	"\x11ShopsTotalRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\"1\n" +
	"\x12ShopsTotalResponse\x12\x1b\n" +
	"\ttotal_num\x18\x01 \x01(\x03R\btotalNum\"\xf8\x01\n" +
	"\fShopsRequest\x123\n" +
	"\fsearch_types\x18\x01 \x03(\x0e2\x10.bcrd.SearchTypeR\vsearchTypes\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x122\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x0e2\x13.bcrd.SortOrderTypeR\tsortOrder\x12\x1a\n" +
	"\blatitude\x18\x06 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\x01R\tlongitude\"1\n" +
	"\rShopsResponse\x12 \n" +
	"\x05shops\x18\x01 \x03(\v2\n" +
	".bcrd.ShopR\x05shops\"?\n" +
	"\vShopRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\x03R\x06shopId\"V\n" +
	"\fShopResponse\x12\x1e\n" +
	"\x04shop\x18\x01 \x01(\v2\n" +
	".bcrd.ShopR\x04shop\x12&\n" +
	"\x0fis_event_period\x18\x02 \x01(\bR\risEventPeriod\"@\n" +
	"\fStampRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\x03R\x06shopId\"7\n" +
	"\rStampResponse\x12&\n" +
	"\x0fnumber_of_times\x18\x01 \x01(\x05R\rnumberOfTimes\"\\\n" +
	"\x15MergeUserStampRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12*\n" +
	"\x11anonymous_user_id\x18\x02 \x01(\tR\x0fanonymousUserId\"5\n" +
	"\x16MergeUserStampResponse\x12\x1b\n" +
	"\tstamp_num\x18\x01 \x01(\x05R\bstampNum*j\n" +
	"\n" +
	"SearchType\x12 \n" +
	"\x1cSEARCH_TYPE_IN_CURRENT_SALES\x10\x00\x12\x17\n" +
	"\x13SEARCH_TYPE_NOT_YET\x10\x01\x12!\n" +
	"\x1dSEARCH_TYPE_IRREGULAR_HOLIDAY\x10\x02*;\n" +
	"\rSortOrderType\x12\x11\n" +
	"\rSORT_ORDER_NO\x10\x00\x12\x17\n" +
	"\x13SORT_ORDER_DISTANCE\x10\x012\xf2\x02\n" +
	"\vBcrdService\x12B\n" +
	"\rGetShopsTotal\x12\x17.bcrd.ShopsTotalRequest\x1a\x18.bcrd.ShopsTotalResponse\x123\n" +
	"\bGetShops\x12\x12.bcrd.ShopsRequest\x1a\x13.bcrd.ShopsResponse\x120\n" +
	"\aGetShop\x12\x11.bcrd.ShopRequest\x1a\x12.bcrd.ShopResponse\x123\n" +
	"\bAddStamp\x12\x12.bcrd.StampRequest\x1a\x13.bcrd.StampResponse\x126\n" +
	"\vDeleteStamp\x12\x12.bcrd.StampRequest\x1a\x13.bcrd.StampResponse\x12K\n" +
	"\x0eMergeUserStamp\x12\x1b.bcrd.MergeUserStampRequest\x1a\x1c.bcrd.MergeUserStampResponseB#Z!github.com/go-to/bcrd_protobuf/pbb\x06proto3"

var (
	file_bcrd_proto_rawDescOnce sync.Once
	file_bcrd_proto_rawDescData []byte
)

func file_bcrd_proto_rawDescGZIP() []byte {
	file_bcrd_proto_rawDescOnce.Do(func() {
		file_bcrd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bcrd_proto_rawDesc), len(file_bcrd_proto_rawDesc)))
	})
	return file_bcrd_proto_rawDescData
}

var file_bcrd_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_bcrd_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_bcrd_proto_goTypes = []any{
	(SearchType)(0),                // 0: bcrd.SearchType
	(SortOrderType)(0),             // 1: bcrd.SortOrderType
	(*Date)(nil),                   // 2: bcrd.Date
	(*Event)(nil),                  // 3: bcrd.Event
	(*Shop)(nil),                   // 4: bcrd.Shop
	(*ShopLocation)(nil),           // 5: bcrd.ShopLocation
	(*ShopTime)(nil),               // 6: bcrd.ShopTime
	(*ShopsTotalRequest)(nil),      // 7: bcrd.ShopsTotalRequest
	(*ShopsTotalResponse)(nil),     // 8: bcrd.ShopsTotalResponse
	(*ShopsRequest)(nil),           // 9: bcrd.ShopsRequest
	(*ShopsResponse)(nil),          // 10: bcrd.ShopsResponse
	(*ShopRequest)(nil),            // 11: bcrd.ShopRequest
	(*ShopResponse)(nil),           // 12: bcrd.ShopResponse
	(*StampRequest)(nil),           // 13: bcrd.StampRequest
	(*StampResponse)(nil),          // 14: bcrd.StampResponse
	(*MergeUserStampRequest)(nil),  // 15: bcrd.MergeUserStampRequest
	(*MergeUserStampResponse)(nil), // 16: bcrd.MergeUserStampResponse
}
var file_bcrd_proto_depIdxs = []int32{
	2,  // 0: bcrd.Event.start_date:type_name -> bcrd.Date
	2,  // 1: bcrd.Event.end_date:type_name -> bcrd.Date
	0,  // 2: bcrd.ShopsRequest.search_types:type_name -> bcrd.SearchType
	1,  // 3: bcrd.ShopsRequest.sort_order:type_name -> bcrd.SortOrderType
	4,  // 4: bcrd.ShopsResponse.shops:type_name -> bcrd.Shop
	4,  // 5: bcrd.ShopResponse.shop:type_name -> bcrd.Shop
	7,  // 6: bcrd.BcrdService.GetShopsTotal:input_type -> bcrd.ShopsTotalRequest
	9,  // 7: bcrd.BcrdService.GetShops:input_type -> bcrd.ShopsRequest
	11, // 8: bcrd.BcrdService.GetShop:input_type -> bcrd.ShopRequest
	13, // 9: bcrd.BcrdService.AddStamp:input_type -> bcrd.StampRequest
	13, // 10: bcrd.BcrdService.DeleteStamp:input_type -> bcrd.StampRequest
	15, // 11: bcrd.BcrdService.MergeUserStamp:input_type -> bcrd.MergeUserStampRequest
	8,  // 12: bcrd.BcrdService.GetShopsTotal:output_type -> bcrd.ShopsTotalResponse
	10, // 13: bcrd.BcrdService.GetShops:output_type -> bcrd.ShopsResponse
	12, // 14: bcrd.BcrdService.GetShop:output_type -> bcrd.ShopResponse
	14, // 15: bcrd.BcrdService.AddStamp:output_type -> bcrd.StampResponse
	14, // 16: bcrd.BcrdService.DeleteStamp:output_type -> bcrd.StampResponse
	16, // 17: bcrd.BcrdService.MergeUserStamp:output_type -> bcrd.MergeUserStampResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_bcrd_proto_init() }
func file_bcrd_proto_init() {
	if File_bcrd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bcrd_proto_rawDesc), len(file_bcrd_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bcrd_proto_goTypes,
		DependencyIndexes: file_bcrd_proto_depIdxs,
		EnumInfos:         file_bcrd_proto_enumTypes,
		MessageInfos:      file_bcrd_proto_msgTypes,
	}.Build()
	File_bcrd_proto = out.File
	file_bcrd_proto_goTypes = nil
	file_bcrd_proto_depIdxs = nil
}
